version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/backend/app

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: speedymeals
      POSTGRES_PASSWORD: speedymeals
      POSTGRES_DB: speedymeals
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
